FORMAT: 1A
HOST: http://blog.acme.com

# Emnify API
The EMnify Service Core implements a RESTful API. Communication with the API is done over HTTP(S) requests with JSON body content and content-type "application/json" with an authentication token as a requirement for every API call.  All API calls must be made over https. 

## Authenticating the API
Initial authentication against the API is done by providing user credentials, the API then returns a token that must be used in all future API calls in the header of the HTTP request as "X-Auth-Token".

The access token will be valid for a certain time period and expire after that, the user will need to re-authenticate then to get a new access token in that case.

For access from applications special access tokens are available that do not expire.

All API calls including the Authentication must be made over secure socket (SSL).

## URL format

All API URLs are following a generic structure like 

    /api/APIVERSION/ENDPOINT/{object_id}

e.g.

    /api/v1/user/123

Also some resources may provide access to further sub-resources

    /api/v1/user/123/tracking

## HTTP verbs

While the API URLs represent the different resources you can work with, you can perform actions on them through different HTTP verbs. 

* GET - retrieves a representation of a resource without side-effects (nothing changes on the server)
* HEAD - retrieves just the resource meta-information (headers) i.e. same as GET but without the response body - also without side-effects
* OPTIONS - returns the actions supported for specified the resource - also without side-effects
* POST - creates a resource
* PUT - (completely) replaces an existing resource
* DELETE - deletes a resource
* PATCH - sax

For HTTP clients that only support POST and GET the method can be alternatively transmitted in the "X-HTTP-Method-Override" header.

## HTTP Headers

Each HTTP request must have at least the following headers:

* Content-Type: application/json
* Accept: application/json
* X-Auth-Token: Access token as received during authentication

## HTTP Return codes

Code  | Description
------------- | -------------
200 OK | Response to a successful GET, also used for a POST if it does not result in a creation
201 Created | Response to a POST that results in a creation, usually will return a Location header pointing to the location of the new resource
204 No Content | Response to a successful request that is not returning a body
400 Bad Request | The request is malformed, e.g. the body cannot be parsed
401 Unauthorized | No or invalid access token provided
403 Forbidden | Access token is valid, but user has no access permissions to the request resource
404 Not Found | A non-existent resource is requested
405 Method Not Allowed | HTTP method being requested isn't allowed
410 Gone | Indicates that the resource at this end point is no longer available.
415 Unsupported Media Type | Incorrect content type was provided as part of the request
422 Unprocessable Entity | Body will return list of validation errors
429 Too Many Requests | Request is rejected due to rate limiting

## Error Handling

The API will return HTTP error codes according to the type of the error, 400 error codes are used for client related issues, 500 error codes for server side issue.

### JSON error representation

400 error codes come with a consumable JSON error representation:

    {
        "error_code" : 1000,
        "error_token" : "InvalidAccessToken"
        "message" : "XYZ failed",
        "description" : "Here comes a detailed description of the error."
    }

Some error codes like ValidationFailed can contain multiple error messages embedded

    {
        "error_code" : 1005,
        "error_token" : "Failed",
        "message" : "Input validation failed",
        "description" : "Here comes a detailed description of the error.",
        "errors" : [
            {
                "error_code" : 2000,
                "error_token" : "InvalidUsername",
                "field" : "username",
                "message" : "Username must be a valid email address"
            },
            {
                "error_code" : 2001,
                "error_token" : "InvalidOrganisationID",
                "field" : "organisation_id",
                "message" : "Organisation ID cannot be blank"
            }
        ]
    }

### List of Error Codes

#### Generic Error Codes

Code  | Description
------------- | -------------
1000 | InvalidAccessToken 
1001 | AuthenticationFailed
1002 | ValidationFailed
1003 | UnknownUsername
1004 | DuplicateUsername
1005 | UnknownUserID
1006 | UnknownEndpointID
1007 | UnknownServiceProfileID

#### Validation Error Codes

Code  | Description
------------- | -------------
2000 | InvalidUsername
2001 | InvalidOrganisationID


# Group Endpoint
Manages endpoints

## List of endpoints [/api/v1/endpoints]
This resources returns the full list of endpoints including details, to which the requesting user has access to. It may also return an empty list.

**Errors**

- InvalidAccessToken

**Response elements (list of)**

Name  | Description
------------- | -------------
id | Unique ID of this endpoint (String)
name | Name of endpoint (string)
tags | Assgined Tags (string)
created | Timestamp when this endpoint was created (Type: ISO 8601 timestamp format)
status | **cheating here** I need an embedded object

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "name": "arduino01",
                    "tags": "arduino, meter, temp",
                    "created": "2014-08-01T08:47:00+00:00",
                    "status": {
                        "id": 1,
                        "description": "ENABLED"
                    },
                    "service_profile": {
                        "id": 1,
                        "name": "Smart Meter"
                    },
                    "tariff_profile": {
                        "id": 3,
                        "name": "Domestic only"
                    },
            
                    "image": "arduino.png",
            
                    "sim": {
                        "id": 788,
                        "iccid": "736826736473829773621",
                        "imsi": "901991234567890",
                        "msisdn": "+88563748761"
                    },
            
                    "imei": "864345678889321",           
                    "ip_address": "10.203.23.75",
            
                    "runtime_data": {
                        "connectivity": "Online",
                        "ggsn_ip_address": "185.56.216.32",
                        "sgsn_ip_address": "82.113.96.21",
                        "msc": "+491790002121",
                        "location": {
                            "country": {
                                "id": 902,
                                "name": "Germany"
                                },
                            "lat": 51.0,
                            "lng": -0.1,
                            "accuracy": 1200.4
                        }
                    },
            
                    "usage_data": {
                        "total" : 23,
                        "tx" : 10,
                        "rx" : 13,
                        "max": 50,
                        "costs": 4.12,
                        "pm_costs": 5.12
                    }
                },
                {
                    "id": 2,
                    "name": "arduino02",
                    "tags": "arduino, meter, temp",
                    "created": "2014-08-19T16:47:00+00:00",
                    "status": {
                        "id": 2,
                        "description": "DISABLED"
                    },
                    "service_profile": {
                        "id": 1,
                        "name": "Smart Meter"
                    },
                    "tariff_profile": {
                        "id": 3,
                        "name": "Domestic only"
                    },
            
                    "image": "arduino.png",
            
                    "sim": {
                        "id": 789,
                        "iccid": "736826736473829773622",
                        "imsi": "901991234567891",
                        "msisdn": "+88563748762"
                    },
            
                    "imei": "864345678897829",           
                    "ip_address": "10.203.23.76",
            
                    "runtime_data": {
                        "connectivity": "Offline"
                    },
            
                    "usage_data": {
                        "total" : 10,
                        "tx" : 5,
                        "rx" : 5,
                        "max": 50,
                        "costs": 2.12,
                        "pm_costs": 5.12
                    }
                },
                {
                    "id": 3,
                    "name": "arduino03",
                    "tags": "arduino, meter, temp",
                    "created": "2014-08-22T16:47:00+00:00",
                    "status": {
                        "id": 2,
                        "description": "DISABLED"
                    },
                    "service_profile": {
                        "id": 1,
                        "name": "Smart Meter"
                    },
                    "tariff_profile": {
                        "id": 4,
                        "name": "World-wide access"
                    },
            
                    "image": "arduino.png",
            
                    "sim": {
                        "id": 790,
                        "iccid": "736826736473829773623",
                        "imsi": "901991234567892",
                        "msisdn": "+88563748763"
                    },
            
                    "imei": "864345678897830",           
                    "ip_address": "10.203.23.77",
            
                    "runtime_data": { 
                        "connectivity": "Offline"
                    },
            
                    "usage_data": {
                        "total" : 22,
                        "tx" : 10,
                        "rx" : 12,
                        "max": 50,
                        "costs": 2.12,
                        "pm_costs": 5.12
                    }
                }
            ]

### List of all endpoints [GET]
Retrive the list of endpoints.

+ Response 200

    [List of endpoints][]
    
### Create a new Endpoint [POST]
To create and endpoint provide provide endpoint JSON object.

*Errors*

- InvalidAccessToken
- ValidationFailed

+ Request (application/json)

            {
                "name": "arduino01",
                "tags": "arduino, meter, temp",
                "status": {
                    "id": 1
                },
                "service_profile": {
                    "id": 2
                },
                "tariff_profile_id": {
                    "id": 3
                },
                "ip_address": "10.203.23.78"
            }

+ Response 201

    + Headers

            Location: https://www.emnify.com/api/v1/endpoint/123

    + Body
    
            [{
                "id": "1",
                "name": "arduino01",
                "tags": "arduino, meter, temp",
                "created": "2014-08-01T08:47:00+00:00",
                "status": {
                    "id": 1,
                    "description": "ENABLED"
                },
                "service_profile": {
                    "id": 1,
                    "name": "Smart Meter"
                },
                "tariff_profile": {
                    "id": 3,
                    "name": "Domestic only"
                },
            
                "image": "arduino.png",
            
                "sim": {
                    "id": 788,
                    "iccid": "736826736473829773621",
                    "imsi": "901991234567890",
                    "msisdn": "+88563748761"
                },
            
                "imei": "864345678889321",           
                "ip_address": "10.203.23.75",
            
                "runtime_data": {
                    "connectivity": "Online",
                    "ggsn_ip_address": "185.56.216.32",
                    "sgsn_ip_address": "82.113.96.21",
                    "msc": "+491790002121",
                    "location": {
                        "country": {
                            "id": 902,
                            "name": "Germany"
                            },
                        "lat": 51.0,
                        "lng": -0.1,
                        "accuracy": 1200.4
                    }
                },
            
                "usage_data": {
                    "total" : 23,
                    "tx" : 10,
                    "rx" : 13,
                    "max": 50,
                    "costs": 4.12,
                    "pm_costs": 5.12
                }
            }]

# Group SIMs
Manages SIMs
